CREATE TABLE IF NOT EXISTS UtBottomA (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    uuid CHAR(36) UNIQUE NOT NULL,
    name VARCHAR(16) NOT NULL
);

CREATE TABLE IF NOT EXISTS UtBottomB (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    a_id INTEGER,
    value INTEGER
);