// Group + version are inherited from the root project (build.gradle).

dependencies {
    api project(':dbm-sql')
    // Uses version defined in: dbm-eternal/gradle/libs.versions.toml
    compileOnly libs.jetbrains.annotations
    implementation libs.hikaricp
    testImplementation libs.bundles.testing
    testImplementation libs.bundles.test.drivers
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

test {
    useJUnitPlatform()
}
